/**
 * Well-known fictional characters and celebrities that a creature must not be
 * named after (SD section 10.2). Lowercase; callers normalise before comparing.
 */
export const BLOCKED_NAMES: readonly string[] = [
  'mickey',
  'minnie',
  'donald duck',
  'goofy',
  'pikachu',
  'mario',
  'luigi',
  'sonic',
  'shrek',
  'elsa',
  'olaf',
  'harry potter',
  'hermione',
  'dumbledore',
  'gandalf',
  'frodo',
  'yoda',
  'darth vader',
  'spongebob',
  'garfield',
  'snoopy',
  'scooby-doo',
  'winnie the pooh',
  'peppa pig',
  'kermit',
  'batman',
  'superman',
  'spider-man',
  'taylor swift',
  'beyonce',
  'elon musk',
  'shakira',
  'einstein',
];
