/**
 * Topics AI text must not touch (SD section 10.2). Deliberately small and
 * all-ages-sensible: gardening words such as "bloom", "weed" or "shoot" are
 * left out on purpose. Lowercase; callers normalise before comparing.
 */
export const SENSITIVE_TERMS: readonly string[] = [
  // Violence and scary content
  'kill',
  'killed',
  'killing',
  'killer',
  'murder',
  'blood',
  'bloody',
  'gun',
  'knife',
  'knives',
  'sword',
  'weapon',
  'bomb',
  'war',
  'die',
  'died',
  'dying',
  'dead',
  'death',
  'corpse',
  'zombie',
  'nightmare',
  'horror',
  'terrifying',
  'suicide',
  'terrorist',
  // Romance and sexual content (swearing-level words are in BLOCKED_WORDS)
  'kiss',
  'kisses',
  'kissed',
  'kissing',
  'boyfriend',
  'girlfriend',
  'romance',
  'romantic',
  'flirt',
  'flirting',
  'dating',
  'naked',
  // Alcohol
  'alcohol',
  'beer',
  'wine',
  'vodka',
  'whisky',
  'whiskey',
  'champagne',
  'cocktail',
  'drunk',
  'booze',
  'hangover',
  // Drugs and smoking
  'drug',
  'cocaine',
  'heroin',
  'cannabis',
  'marijuana',
  'cigarette',
  'cigar',
  'tobacco',
  'vape',
  'vaping',
  // Politics
  'politics',
  'political',
  'politician',
  'election',
  'president',
  'prime minister',
  'government',
  'parliament',
  'democrat',
  'republican',
  'nazi',
  // Religion
  'god',
  'goddess',
  'jesus',
  'christ',
  'allah',
  'buddha',
  'bible',
  'quran',
  'koran',
  'church',
  'mosque',
  'synagogue',
  'religion',
  'religious',
  'pray',
  'prayer',
  'praying',
  'hell',
  'satan',
  'devil',
];
